-- Create database
CREATE DATABASE IF NOT EXISTS TIGEREYEDB;
USE TIGEREYEDB;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users
(
UID 					INTEGER			ZEROFILL PRIMARY KEY AUTO_INCREMENT,
Name					VARCHAR(20)		NOT NULL,
Email					VARCHAR(100)	NOT NULL,
Password				VARCHAR(15)		NOT NULL,
);