# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigereyeAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'events'},
        ),
    ]
