# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigereyeAPP', '0002_auto_20170301_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
