# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigereyeAPP', '0003_auto_20170304_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
