# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigereyeAPP', '0004_auto_20170304_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('open_time', models.DateTimeField(default=datetime.datetime.now)),
                ('close_time', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500)),
                ('area_image', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'social areas',
            },
        ),
    ]
